kit:
  name: "Training manifests"
  link: "http://github.com/qubell-bazaar/training/"
  applications:
    - name: "PetClinic"
      manifest: https://raw.github.com/qubell-bazaar/training/master/petclinic.yml
    - name: "Database"
      manifest: https://raw.github.com/qubell-bazaar/training/master/mysql.yml
    - name: "Application Server"
      manifest: https://raw.github.com/qubell-bazaar/training/master/tomcat.yml
    - name: "Load Balancer"
      manifest: https://raw.github.com/qubell-bazaar/training/master/haproxy.yml
  provider:
    name: ""
    link: ""
  documentation:
    overview: ""

